version: '3.9'

services:

  backend:
    build:
      context: .

    ports:
      - '8000:8000'
    restart: always

    depends_on:
      - db
    volumes:
      - .:/app/
  db:
    image: postgres:16.2
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: pomodoro
    volumes:
      - .:/app/
  
  