version: '3.9'

services:

  backend:
    build:
      context: .
    ports:
      - '8000:8000'
    restart: always
    depends_on:
      - db
    volumes:
      - .:/app/
  db:
    image: postgres:16.2
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: pomodoro
    volumes:
      - .:/app/db_data/
  
  redis:
    image: redis:latest
    container_name: redis_container
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data:
    driver: local